stages:
  - pre-test
  - build

# === Анализ кода через SonarQube ===
sonarqube-check:
  stage: pre-test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  allow_failure: true
  only:
    - main

# === Сборка Docker-образа и пуш в Harbor ===
build:
  image:
    name: docker:28.1.1-dind
    entrypoint: ["dockerd-entrypoint.sh"]
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - dockerd-entrypoint.sh &
    - until docker info; do sleep 1; done;
  script:
    - docker login harbor.bankingapi.ru/brezhnev_test -u student6_student6 --password SzhL2kstIwh0WwVnhiukmqBqxGrjt6vK
    - docker build -t harbor.bankingapi.ru/brezhnev_test/pytest:latest .
    - docker push harbor.bankingapi.ru/brezhnev_test/pytest:latest


